### ISSUE TITLE
Textfield wasn't showing underneath Settings tab in Silverstripe

### ISSUE THREAD

**Issue by IntellectProductions** [silverstripesk/silverstripe-disqus#12]
The text field for the disqus identifier wasn't showing up underneath the settings tab. I was confused since in the readme, it said "Behavior" and that has changed.

```
	private static $db = array(
		'customDisqusIdentifier' => 'Varchar(32)',
        'ProvideComments' => 'Boolean(1)'
	);
	
	public function updateSettingsFields(FieldList $fields) {
		
		$fields->addFieldToTab('Root.Settings', new TextField("customDisqusIdentifier", "customDisqusIdentifier"));
        $fields->addFieldToTab('Root.Settings', new CheckboxField('ProvideComments', 'Provide Comments'));
        return $fields;
		
	}
```

That's what I updated the function to in the DisqusDecorator.php file. It now shows the text field and the ProvideComments checkbox.. the DisqusPageComments() method was looking to see if $this->owner->ProvideComments was true.. and there was no such field so it wasn't even displaying the comments on the pages.

Hopefully this helps others that was having problems integrating it!

**Comment by silverstripesk** [comment]
As default comments module is using ProvideComments column, I just stopped to use is. If Comments module installed, this checkbox is common for comments module and this module. In your template you can decide which one to use. If you don't use comments module, disqus comments will be shown on all activated pagetypes. README changed.
